### ISSUE TITLE
Does not work with hair and fur modifier

### ISSUE THREAD

**Issue by tcheng00** [GPUOpen-LibrariesAndSDKs/RadeonProRenderMaxPlugin#4]
Preview and final render windows do not show hair and fur.

**Comment by bsavery** [comment]
Hi there.  Our plan going forward is to support 3DS Max through the USD / Hydra system which Autodesk outlined here:  https://makeanything.autodesk.com/events/vision-series-2020#Film-TV-Games

So for now we are in "maintenance" mode of fixing crashes, stay tuned for more info.
